# Generated by Django 4.1.6 on 2023-04-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_remove_review_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
